sudo: required
language: bash

services:
    - docker

git:
    depth: 1

env:
    global:
        - "IMAGE_NAME=gableroux/unity3d:2018.3.12f1"
        - "BUILD_NAME=SoftwareEngineeringSimulator"

before_install:
    - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
    - git lfs pull
    - openssl aes-256-cbc -K $encrypted_6c9d1d6ca102_key -iv $encrypted_6c9d1d6ca102_iv -in ci/Unity_v2018.x.ulf.enc -out ci/Unity_v2018.x.ulf -d
    - export UNITY_LICENSE_CONTENT=`cat ci/Unity_v2018.x.ulf`
    - rm ci/Unity_v2018.x.ulf
    - docker pull $IMAGE_NAME
    
jobs:
    include:
        - 
            stage: test
            script: "chmod +x ./ci/* && ./ci/docker_test.sh"
            env: TEST_PLATFORM=playmode
            addons:
                artifacts:
                    target_paths:
                        - "$(pwd)/$TEST_PLATFORM-results.xml"
        # -   
        #     stage: build
        #     scr

notifications:
    webhooks: 
        urls:
            - https://fathomless-fjord-24024.herokuapp.com/notify
        on-start: always
