sudo: required
language: bash

services:
    - docker

env:
    global:
        - "IMAGE_NAME=gableroux/unity3d:2018.3.12f1"
        - "BUILD_NAME=SoftwareEngineeringSimulator"

before-install:
    - openssl aes-256-cbc -K $encrypted_6c9d1d6ca102_key -iv $encrypted_6c9d1d6ca102_iv -in Unity_v2018.x.ulf.enc -out ./Unity_v2018.x.ulf -d
    - export UNITY_LICENSE_CONTENT=`cat Unity_v2018.x.ulf`
    - rm Unity_v2018.x.ulf
    - docker pull $IMAGE_NAME
    
jobs:
    include:
        - 
            stage: test
            script: "chmod +x ./ci/* && ./ci/docker_test.sh"
            env: TEST_PLATFORM=editmode
            addons:
                artifacts:
                    target_paths:
                        - "$(pwd)/$TEST_PLATFORM-results.xml"

